import os
import sys
import re

def split(pdb_input,pdb_folder):

# Generate the recording folder
   target_folder=pdb_folder
   if not os.path.exists(target_folder):
       os.mkdir(target_folder)

# Split the whole 
   PDB=[] 
   PDBs=[]
   with open(pdb_input,'r') as pdb_one:
       lines = pdb_one.readlines()
       iline=0
       i=0 
       for line in lines:
           i = i+1 
           if len(line.split()) != 0:
               #print("line[1:6] :", line[0:6] ) 
               if line[0:6] == "HETATM" or line[0:4] == "ATOM" :
                   #lline=line[0:78]+" \n"
                   #print(line) 
                   #print(lline) 
                   #exit(0)
                   if len(PDB) > 0 : 
                   #print("line[21:26]  :",line[21:26] ) 
                   #print("PDB[iline-1] :",PDB)
                       if line[21:26] != PDB[iline-1][21:26] :
                           PDBs.append(PDB)
                           PDB=[] 
                           iline=0
                   PDB.append(line)
                   iline=iline+1
                   if i == len(lines): 
                       PDBs.append(PDB)

   print("len(PDBs) : ",len(PDBs))

   for i in range(len(PDBs)):
       pdb_output = target_folder+'/'+ str(i+1).rjust(8,'0') +".pdb"
       with open(pdb_output,'w') as fpdb:
           fpdb.write("COMPND    " + str(i+1) + "\n")
           fpdb.write("AUTHOR    GENERATED BY ParaEngine\n")
           for j in range(len(PDBs[i])):
               #print(PDBs[i][j])
               fpdb.write(PDBs[i][j])
           fpdb.write("END")    
            
   for i in range(len(PDBs)):
       pdb_output = target_folder+'/'+ str(i+1).rjust(8,'0') +".pdb"
       sdf_output = target_folder+'/'+ str(i+1).rjust(8,'0') +".sdf"
       os.system("obabel -i pdb " + pdb_output + " -o sdf > " + sdf_output)
       os.system("rm " + pdb_output)

#   exit(0)

# Generate the valid sdfs
#print(len(npdb))

